# Generated by Django 4.0.2 on 2022-02-21 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_product_brand_product_category_product_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
