# Generated by Django 4.0.2 on 2022-02-23 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='title',
        ),
    ]
